/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Cortinez Juan José
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OnOf = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTF1 = new org.edisoncor.gui.textField.TextFieldRoundBackground();
        jBsuma = new javax.swing.JButton();
        jRon = new javax.swing.JRadioButton();
        jB3 = new javax.swing.JButton();
        jBresta = new javax.swing.JButton();
        jB4 = new javax.swing.JButton();
        jRoff = new javax.swing.JRadioButton();
        jBmultiplicacion = new javax.swing.JButton();
        jB5 = new javax.swing.JButton();
        jBdivision = new javax.swing.JButton();
        jB6 = new javax.swing.JButton();
        jBreset = new javax.swing.JButton();
        jB7 = new javax.swing.JButton();
        jBpotencia = new javax.swing.JButton();
        jB8 = new javax.swing.JButton();
        jBraiz = new javax.swing.JButton();
        jB9 = new javax.swing.JButton();
        jB0 = new javax.swing.JButton();
        jBporcentaje = new javax.swing.JButton();
        jBpunto = new javax.swing.JButton();
        jB1 = new javax.swing.JButton();
        jBigual = new javax.swing.JButton();
        jB2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setBackground(new java.awt.Color(51, 51, 51));
        setLocation(new java.awt.Point(350, 200));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        jTF1.setBackground(new java.awt.Color(0, 0, 0));
        jTF1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 102, 102), null, null));
        jTF1.setForeground(new java.awt.Color(204, 0, 0));
        jTF1.setCaretColor(new java.awt.Color(204, 0, 0));
        jTF1.setDescripcion(".");
        jTF1.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N

        jBsuma.setBackground(new java.awt.Color(0, 0, 0));
        jBsuma.setForeground(new java.awt.Color(0, 204, 153));
        jBsuma.setText("+");

        jRon.setBackground(new java.awt.Color(51, 51, 255));
        OnOf.add(jRon);
        jRon.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jRon.setForeground(new java.awt.Color(0, 204, 0));
        jRon.setText("ON");

        jB3.setBackground(new java.awt.Color(0, 0, 0));
        jB3.setForeground(new java.awt.Color(0, 153, 255));
        jB3.setText("3");

        jBresta.setBackground(new java.awt.Color(0, 0, 0));
        jBresta.setForeground(new java.awt.Color(0, 204, 153));
        jBresta.setText("-");

        jB4.setBackground(new java.awt.Color(0, 0, 0));
        jB4.setForeground(new java.awt.Color(0, 153, 255));
        jB4.setText("4");

        jRoff.setBackground(new java.awt.Color(51, 51, 255));
        OnOf.add(jRoff);
        jRoff.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jRoff.setForeground(new java.awt.Color(0, 204, 0));
        jRoff.setSelected(true);
        jRoff.setText("OFF");

        jBmultiplicacion.setBackground(new java.awt.Color(0, 0, 0));
        jBmultiplicacion.setForeground(new java.awt.Color(0, 204, 153));
        jBmultiplicacion.setText("*");

        jB5.setBackground(new java.awt.Color(0, 0, 0));
        jB5.setForeground(new java.awt.Color(0, 153, 255));
        jB5.setText("5");

        jBdivision.setBackground(new java.awt.Color(0, 0, 0));
        jBdivision.setForeground(new java.awt.Color(0, 153, 153));
        jBdivision.setText("/");

        jB6.setBackground(new java.awt.Color(0, 0, 0));
        jB6.setForeground(new java.awt.Color(0, 153, 255));
        jB6.setText("6");

        jBreset.setBackground(new java.awt.Color(0, 0, 0));
        jBreset.setForeground(new java.awt.Color(0, 204, 153));
        jBreset.setText("C");

        jB7.setBackground(new java.awt.Color(0, 0, 0));
        jB7.setForeground(new java.awt.Color(0, 153, 255));
        jB7.setText("7");

        jBpotencia.setBackground(new java.awt.Color(0, 0, 0));
        jBpotencia.setForeground(new java.awt.Color(0, 204, 153));
        jBpotencia.setText("^");

        jB8.setBackground(new java.awt.Color(0, 0, 0));
        jB8.setForeground(new java.awt.Color(0, 153, 255));
        jB8.setText("8");

        jBraiz.setBackground(new java.awt.Color(0, 0, 0));
        jBraiz.setForeground(new java.awt.Color(0, 204, 153));
        jBraiz.setText("sqrt");

        jB9.setBackground(new java.awt.Color(0, 0, 0));
        jB9.setForeground(new java.awt.Color(0, 153, 255));
        jB9.setText("9");

        jB0.setBackground(new java.awt.Color(0, 0, 0));
        jB0.setForeground(new java.awt.Color(0, 153, 255));
        jB0.setText("0");

        jBporcentaje.setBackground(new java.awt.Color(0, 0, 0));
        jBporcentaje.setForeground(new java.awt.Color(0, 204, 153));
        jBporcentaje.setText("%");

        jBpunto.setBackground(new java.awt.Color(0, 0, 0));
        jBpunto.setForeground(new java.awt.Color(51, 255, 51));
        jBpunto.setText(".");

        jB1.setBackground(new java.awt.Color(0, 0, 0));
        jB1.setForeground(new java.awt.Color(0, 153, 255));
        jB1.setText("1");

        jBigual.setBackground(new java.awt.Color(0, 0, 0));
        jBigual.setForeground(new java.awt.Color(51, 255, 51));
        jBigual.setText("=");

        jB2.setBackground(new java.awt.Color(0, 0, 0));
        jB2.setForeground(new java.awt.Color(0, 153, 255));
        jB2.setText("2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBpunto, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jB0))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jB7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jB8))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jB4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jB5))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jB1)
                                .addGap(28, 28, 28)
                                .addComponent(jB2)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jB3)
                            .addComponent(jB6)
                            .addComponent(jB9)
                            .addComponent(jBigual))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBsuma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBresta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBmultiplicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBdivision, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBporcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBraiz)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jBpotencia)))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jRoff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jRon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jBreset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jB0, jB1, jB2, jB3, jB4, jB5, jB6, jB7, jB8, jB9, jBigual, jBpunto});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBdivision, jBmultiplicacion, jBporcentaje, jBpotencia, jBraiz, jBreset, jBresta, jBsuma});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jB2)
                        .addComponent(jB3)
                        .addComponent(jBsuma, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jB1))
                    .addComponent(jBreset, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jB4)
                            .addComponent(jB5)
                            .addComponent(jB6)
                            .addComponent(jBresta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jB7)
                            .addComponent(jB8)
                            .addComponent(jB9)
                            .addComponent(jBmultiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBraiz))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBpunto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jB0)
                                .addComponent(jBigual)
                                .addComponent(jBdivision, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jBporcentaje))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBpotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRon))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRoff)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jB0, jB1, jB2, jB3, jB4, jB5, jB6, jB7, jB8, jB9, jBigual, jBpunto});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBdivision, jBmultiplicacion, jBporcentaje, jBpotencia, jBraiz, jBreset, jBresta, jBsuma});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup OnOf;
    public javax.swing.JButton jB0;
    public javax.swing.JButton jB1;
    public javax.swing.JButton jB2;
    public javax.swing.JButton jB3;
    public javax.swing.JButton jB4;
    public javax.swing.JButton jB5;
    public javax.swing.JButton jB6;
    public javax.swing.JButton jB7;
    public javax.swing.JButton jB8;
    public javax.swing.JButton jB9;
    public javax.swing.JButton jBdivision;
    public javax.swing.JButton jBigual;
    public javax.swing.JButton jBmultiplicacion;
    public javax.swing.JButton jBporcentaje;
    public javax.swing.JButton jBpotencia;
    public javax.swing.JButton jBpunto;
    public javax.swing.JButton jBraiz;
    public javax.swing.JButton jBreset;
    public javax.swing.JButton jBresta;
    public javax.swing.JButton jBsuma;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JRadioButton jRoff;
    public javax.swing.JRadioButton jRon;
    public org.edisoncor.gui.textField.TextFieldRoundBackground jTF1;
    // End of variables declaration//GEN-END:variables
}
